### ISSUE TITLE
error occurred when used with java 

### ISSUE THREAD

**Issue by Debojit219** [agrawal-d/cph#94]
As I click on "Run All" I get an error msg saying:
Standard error:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: The_One_Who_Knocks_ has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by apurv-patani** [comment]
I think it's a version mismatch problem. You can take a look at [this](https://www.baeldung.com/java-lang-unsupportedclassversion).
Also, what commands are you using to compile and run on terminal?

**Comment by Debojit219** [comment]
There was a problem previously. it wasn't running and giving the error code
as I mention in GitHub. But now it's running fine. But it shows "Failed"
despite all TCs give the correct output.
Am attaching a screenshot for reference.
Thank you!
[image: image.png]

**Comment by apurv-patani** [comment]
Hey, does it work now? Btw you didn't attach the screenshot above.
